### ISSUE TITLE
2 bugs 

### ISSUE THREAD

**Issue by Andrey309a** [Klayeryt/Welcome#16]
**Also a strange thing happens in the chat, it seems to slow down the chat and when a new message has to appear in the chat, a previous message appears again and then the older message is removed and the new message appears (either something written by the players or a console message).**

https://discord.com/channels/1158265218279948351/1158268113209536592/1320478668560011355

[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> MaxMind.GeoIP2.Exceptions.AddressNotFoundException: The address 127.0.0.1 is not in the database.
nNullResponse)
   at MaxMind.GeoIP2.DatabaseReader.Country(String ipAddress)
   at Main.Main.GetCountry(String ipAddress) in C:\Users\sergi\Downloads\Welcome-Version-1.0.0\Welcome-Version-1.0.0\Main.cs:line 78
   at Main.Main.OnPlayerDisconnect(EventPlayerDisconnect event, GameEventInfo info) in C:\Users\sergi\Downloads\Welcome-Version-1.0.0\Welcome-Version-1.0.0\Main.cs:line 117
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by Andrey309a** [comment]
> -

Video https://www.dropbox.com/scl/fi/bqj8ihrmdgi3x39qcazwd/welcom_slow_bug.mp4?rlkey=4i8mc2qwrt2r59ccxv996sef2&st=tfesxaxh&dl=0

**Comment by Klayeryt** [comment]
Андрей, откати версию плагина до старой, полное получение локации игрока не совсем корректно работает. Используй revert-12-version-1.0.0
